#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your own window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

exec startxfce4
#exec enlightenment_start
#exec startkde
# ... or the Window Manager of your choice
